### PR TITLE
master

### PR DESCRIPTION
**Pull request by bugabinga**
- bugfix: handle windows-style path separator

### CODE REVIEW

**Comment by terror** [comment]
Hey @bugabinga, I've went ahead and made my own PR for updating dependencies (#7), I usually do this using `cargo upgrade` (see: https://github.com/killercup/cargo-edit) instead of specifying a `*` for each of them. I am interested in the windows path separator fix however, you can either modify this PR to include the change without updating the dependencies or scrapping it and making a new PR, either works for me.

**Comment by bugabinga** [comment]
Okay, but it will have to wait until monday if you can wait that long ;)

**Comment by bugabinga** [comment]
Hopefully I used the correct git-fu to undo the update commit.

**Comment by terror** [comment]
Closing due to inactivity, fixed in #8

**Pull request closed without merging**
